---
title: "Graphing Using ggplot Part-1"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
```

```{r}
# Load the mpg dataset
data('mpg')
mpgData = mpg

# Print the first five rows (or samples) in the data frame
head(mpgData, 5)
str(mpgData)

```

```{r}
foodData=read.csv('Data/food-texture.csv', header = TRUE, row.names = 1)
head(foodData)
str(foodData)
```

```{r}
#add another column to dataframe called Taste
#foodData['Taste'] = sample(c('poor','fair','good','very good'), replace = TRUE, nrow(foodData), p=c(0.25,0.25,0.25,0.25))
```

```{r}
continuous_cols = c('oil' , 'Density',  'Crisp', 'Fracture', 'Hardness')
categorical_cols = c('Crispy', 'Taste')

```

```{r}
#convert categorical columns to factor type
foodData[categorical_cols]=lapply(foodData[categorical_cols], factor)
str(foodData)
```

```{r}
#to write the added column Taste to CSV file(foodData)
#write.csv(foodData, 'Data/food-texture.csv')
```

SCATTERPLOT

```{r}
p = ggplot(data = foodData) + 
  geom_point(aes(x=Oil, y=Density))
p
```

```{r}
p = ggplot(data = foodData) + 
  geom_point(aes(x=Oil, y=Density, color=Crispy))
p
```

BOXPLOT

```{r}
p = ggplot(data = foodData) + 
  geom_boxplot(aes(x=Crispy, y=Density))
p
```

```{r}
foodData['Crispy'] == 8
foodData[foodData['Crispy']==8, ]
den8=foodData[foodData['Crispy']==8,'Density']
den8

```

```{r}
den10=foodData[foodData['Crispy']==10,'Density']
den10
mean(den10)
den10-mean(den10)
#squared mean centerd value
(den10-mean(den10))^2
#squared deviation
mean((den10-mean(den10))^2) #mean of squared deviation from the average= this is variance
sqrt(mean((den10-mean(den10))^2)) #standard deviation
var(den10)

#to calc Percentile
median(den10)
den10 <= median(den10)
mean(den10 <= median(den10))*100
sum(den10 <= median(den10))
quantile(den10, 0.25) #25th percentile of density value
quantile(den10, 0.5) #median is 50th percentile
quantile(den10, 0.75) #75th percentile
quantile(den10, 0.75)-quantile(den10, 0.25) #IQR
```

```{r}
den13=foodData[foodData['Crispy']==13,'Density']
den13

mean(den13)
median(den13)

sqrt(mean((den13-mean(den13))^2)) #standard deviation
var(den13)

sum(den13 <= median(den13))

quantile(den13, 0.25) #25th percentile of density value
quantile(den13, 0.5) #median is 50th percentile
quantile(den13, 0.75)
quantile(den13, 0.75)-quantile(den13, 0.25)
```

HISTOGRAM

```{r}
p = ggplot(data = foodData) + 
  geom_histogram(aes(x=Density), binwidth = 100, color='blue')

#for only whose crispy value is 13
p = ggplot(data = foodData[foodData$Crispy==13, ]) + 
  geom_histogram(aes(x=Density), binwidth = 100, color='blue')
p
```

BARPLOT

```{r}
p = ggplot(data = foodData) + 
  geom_bar(aes(x=Crispy) , color='blue')
p
```



```{r}
# Initiate the ggplot() function binding to the car data frame
ggplot(data = mpgData)

# Create a plot object
p1 = ggplot(data = mpgData)

# Use the aes() function to specify the aesthetic mapping, that is, which variables
# should be plotted
p1 = ggplot(data = mpgData, aes(x = disp, y = hwy))

# Use the geom_ type functions to add geometric elements
p1 = ggplot(data = mpgData, aes(x = displ, y = hwy)) +
  geom_point()

#local aesthetic
#p1 = ggplot(data = mpgData) + geom_point(aes(x = displ, y = hwy))

# Add labels and title
p1 = p1 + labs(x = 'Displacement (litres)', y = 'Mileage (MPG)', title = 'Mileage vs. Displacement')
p1
```


```{r}
# Map aesthetics to variables

# Map the color aesthetic to the class variable
p2 = ggplot(data = mpgData) +
  geom_point(mapping = aes(x = displ, y = hwy))
p2
```

```{r}
# Map aesthetics to variables

# Map the size (or alpha or shape) aesthetic to the class variable
p3 = ggplot(data = mpgData) +
  geom_point(aes(x = displ, y = hwy))
p3
```

```{r}
# Set aesthetic manually

# Mark the points blue in color, square in shape, and fixed size
p4 = ggplot(data = mpgData) +
  geom_point(aes(x = displ, y = hwy, shape=drv, color=class)) + labs(x = 'Displacement (litres)', y = 'Mileage (MPG)', title = 'Mileage vs. Displacement')

p4
```

```{r}
#how do we relate a continuous and categorical feature?
p5=ggplot(data=mpgData) + geom_boxplot(aes(x=class, y=hwy)) + labs(x= 'Vehicle Class',  y='Mileage(MPG)', title='Mileage vs. Vehicle Class')
p5
```


```{r}
# Add additional variables using facets

# Plot mileage w.r.t. each class individually
ggplot(data = mpgData) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(, nrow = 2)
```

```{r}
# Plot mileage w.r.t drive train and number of cylinders
ggplot(data = mpgData) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid()
```

```{r}
# A quick exercise on facet plotting with filtering of samples
# Investigate the number of levels in the cyl feature
factor()

# How many cars of each cyl type are there?
mpgData %>% 

# Filter samples with 3 and 5 cylinder cars (which are very rare)
# mpgData = mpgData %>% filter(!(? %in% c(?, ?)))
# 
# head(mpgData, 5)
# 
# # Map the color aesthetic to the cyl variable
# p5 = ggplot(data = mpgData) +
#   geom_point(mapping = aes(x = displ, y = hwy))
# p5
```


